CREATE TABLE `diagnostics` (
	`id` text PRIMARY KEY NOT NULL,
	`session_id` text NOT NULL,
	`created_at` integer NOT NULL,
	`source` text,
	`completion_time_sec` integer,
	`target_score` text NOT NULL,
	`grade` text NOT NULL,
	`test_date` text NOT NULL,
	`sat_history` text NOT NULL,
	`q5` text NOT NULL,
	`q6` text NOT NULL,
	`q7` text NOT NULL,
	`q8` text NOT NULL,
	`q9` text NOT NULL,
	`q10` text NOT NULL,
	`q11` text NOT NULL,
	`q12` text NOT NULL,
	`hours_per_week` text NOT NULL,
	`timing` text NOT NULL,
	`review_mistakes` text NOT NULL,
	`prep_status` text NOT NULL,
	`worried_about` text NOT NULL,
	`first_name` text NOT NULL,
	`whatsapp` text NOT NULL,
	`school` text,
	`respondent_type` text NOT NULL,
	`consent` integer NOT NULL,
	`math_raw` integer NOT NULL,
	`rw_raw` integer NOT NULL,
	`overall_band` text NOT NULL,
	`confidence` text NOT NULL,
	`archetype` text NOT NULL,
	`target_num` integer NOT NULL,
	`current_mid` integer NOT NULL,
	`gap` integer,
	`timeline_verdict` text NOT NULL,
	`recommended_program` text NOT NULL,
	`lead_score` real NOT NULL,
	`lead_status` text NOT NULL,
	`result_payload` text NOT NULL,
	`result_sent` integer DEFAULT 0 NOT NULL,
	`followup_status` text DEFAULT 'None' NOT NULL,
	`outcome` text DEFAULT '-' NOT NULL,
	`notes` text
);
--> statement-breakpoint
CREATE TABLE `events` (
	`id` text PRIMARY KEY NOT NULL,
	`session_id` text NOT NULL,
	`created_at` integer NOT NULL,
	`type` text NOT NULL,
	`question_index` integer,
	`meta` text
);
